config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'subjects#index'
  get 'subjects/index'
  get 'posts/search' => 'posts#search', as: :post_search
  get 'subjects/show/:id' => 'subjects#show', as: :subjects_show
  post 'subjects/create' => 'subjects#create'
  post 'posts/create' => 'posts#create', as: :post_create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :subject
  with_options presence: true do
    validates :content
    validates :period
    validates :rate
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  validates :name,
      presence: true,
      uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def search
    @keyword = params[:keyword]
    @posts = PostsService.search(params[:keyword], params[:sort])
  end

  def create
    @post = Post.new(params[:post].permit(:subject_id, :content, :instructor, :period, :rate))
    @post.save
    redirect_to subjects_show_path(params[:post]['subject_id'])
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subjects = Subject.all
    @newSubject = Subject.new
  end

  def show
    @subject = Subject.find(params[:id])
    @newPost = Post.new(:subject_id => params[:id])
    if params[:sort]
      @posts = Post.where(subject_id: params[:id]).order("#{params[:sort]} DESC")
    else
      @posts = Post.where(subject_id: params[:id]).order(created_at: "DESC")
    end
    @periodList = SubjectsService.getPeriodList()
  end

  def create
    @subject = Subject.new(params[:subject].permit(:name))
    @subject.save
    redirect_to subjects_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eval</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Norican&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <div class="brand-logo center" style="font-family: 'Norican', cursive;">
            <%= link_to "Eval", subjects_index_path, data: {"turbolinks" => false} %>
          </div>
          <ul class="right hide-on-med-and-down">
            <li>
          <form action="/posts/search" method="get">
            <div class="input-field">
              <input id="keyword" name="keyword" type="search" placeholder="全ての投稿を検索">
              <label class="label-icon" for="search"><i class="material-icons">search</i></label>
              <i class="material-icons">close</i>
            </div>
          </form>
            </li>
          </ul>
        </div>
      </nav>
    </div>

    <div class="container main">
      <%= yield %>
    </div>

    <div class="fixed-action-btn">
      <p id="pageTop" class="right btn-floating btn-large"><i class="material-icons">arrow_upward</i></p>
    </div>

    <table border="0" cellspacing="0" cellpadding="0" style="display: none;"><tr><td align="center"><a href="http://www.rays-counter.com/"><img src="http://www.rays-counter.com/d445_f8_002/5d873f064e1ba/" alt="アクセスカウンター" border="0"></a></td></tr><tr><td align="center"><img src="http://www.rays-counter.com/images/counter_01.gif" border="0"><img src="http://www.rays-counter.com/images/counter_02.gif" border="0"><img src="http://www.rays-counter.com/images/counter_03.gif" border="0"><img src="http://www.rays-counter.com/images/counter_04.gif" border="0" ><img src="http://www.rays-counter.com/images/counter_05.gif" border="0"></td></tr></table>

    <footer class="page-footer">
      <div class="container">
        Copyright © 2019 black315. All rights reserved.
      </div>
    </footer>
  </body>
</html>

app/views/posts/search.html.erb
<h5><%= @keyword %>の検索結果</h5>
<div class="input-field">
  <%= hidden_field_tag 'key', @keyword %>
  <input type="hidden" name="href" value="/posts/search">
  <select name="sort">
    <option value="" disabled selected>並び順</option>
    <option value="period">最近の授業</option>
    <option value="rate">評価が高い順</option>
  </select>
</div>
<ul>
  <% @posts.each do |post| %>
    <div class="post z-depth-3">
      <div class="post-content">
        <div class="chip z-depth-1">
          <%= post.subject.name %>
        </div>
        <div>
          <%= post.content %>
        </div>
        <hr>
        <div>
          <div class="inline">担当者　<%= post.instructor %></div>
          <div class="inline">投稿者　<%= post.period %>期</div>
          <div class="inline">
            評価　
            <div class="star-ratings-sprite inline">
              <span style="width:<%= post.rate %>%" class="star-ratings-sprite-rating"></span>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</ul>

app/views/subjects/index.html.erb
<h1>Courses</h1>
<div>
  <div class="row">
    <div class="right">
      <input type="button" id="new-subject" class="waves-effect waves-light btn" value="追加する" />
    </div>
  </div>
  <div class="new-form" style="display: none">
  <%= form_for @newSubject, :url => {:action => 'create'} do |f| %>
    <label>科目名</label>
    <%= f.text_field :name %>
    <%= f.submit "追加", :class => "waves-effect waves-light btn" %>
  <% end %>
  </div>
</div>
<ul>
  <% @subjects.each do |subject| %>
    <div class="subject z-depth-3">
      <div class="subject-content">
        <%= link_to subject.name, subjects_show_path(subject.id), data: {"turbolinks" => false} %>
      </div>
    </div>
  <% end %>
</ul>

app/views/subjects/show.html.erb
<h1><%= @subject.name %></h1>
<div>
  <div class="row">
    <div class="right">
        <input type="button" id="new-post" class="waves-effect waves-light btn" value="追加する" />
    </div>
  </div>
  <div class="new-form" style="display: none">
  <%= form_for @newPost, :url => post_create_path do |f| %>
    <label>内容</label>
    <%= f.text_area :content %>
    <label>担当者</label>
    <%= f.text_field :instructor %>
    <div class="input-field col s12">
      <%= f.select :period, @periodList.map { |period| [period, period] }, :prompt => "選択してください" %>
      <label>期</label>
    </div>
    <div class="input-field col s12">
      <%= f.select :rate, [[5, 100], [4, 80], [3, 60], [2, 40], [1, 20]], :prompt => "選択してください" %>
      <label>評価</label>
    </div>
    <%= f.hidden_field :subject_id %>
    <%= f.submit "追加", :class => "waves-effect waves-light btn" %>
  <% end %>
  </div>
</div>
<div class="input-field">
  <input type="hidden" name="href" value="/subjects/show/<%= @subject.id %>">
  <select name="sort">
    <option value="" disabled selected>並び順</option>
    <option value="period">最近の授業</option>
    <option value="rate">高評価</option>
  </select>
</div>
<% @posts.each do |post| %>
  <div class="post z-depth-3">
    <div class="post-content">
      <div>
        <%= post.content %>
      </div>
      <hr>
      <div>
        <div class="inline">担当者　<%= post.instructor %></div>
        <div class="inline">投稿者　<%= post.period %>期</div>
        <div class="inline">
          評価　
          <div class="star-ratings-sprite inline">
            <span style="width:<%= post.rate %>%" class="star-ratings-sprite-rating"></span>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>